name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        
    - name: Compile program
      run: g++ "Quis Kasir.cpp" -o kasir
      
    - name: Run program
      run: ./kasir
